//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCostos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Proyectos = new HashSet<Proyectos>();
        }
    
        public long NumeroIdentificacion { get; set; }
        public string TipoIdentificacion { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> NumeroTelefonico { get; set; }
        public string CorreoElectronico { get; set; }
        public string CorreoElectronicoCopia { get; set; }
        public Nullable<int> CodigoTelefonico { get; set; }
        public int IDProvincia { get; set; }
        public int IDCanton { get; set; }
        public int IDDistrito { get; set; }
        public string Direccion { get; set; }
    
        public virtual Cantones Cantones { get; set; }
        public virtual Distritos Distritos { get; set; }
        public virtual Provincias Provincias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyectos> Proyectos { get; set; }
    }
}
