//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCostos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodGenerar
    {
        public int IdCodigo { get; set; }
        public string NombreProyecto { get; set; }
        public int Secuencia { get; set; }
    }
}
